- name: Common Configuration
  hosts: k3s_workers
  become: yes

  tasks:

    - name: Update packages
      dnf:
        name: "*"
        state: latest

    - name: Install curl
      dnf:
        name: curl
        state: present
